pipeline {

    agent any

    tools {
        nodejs 'nodejs'
    }
    stages {
        stage("Install Dependencies") {
            steps {
                dir("bdlist-backend/") {
                    sh 'pnpm i'
                }
            }
        }
        stage ("Transpile TypeScript to JavaScript") {
            steps {
                dir("bdlist-backend/") {
                    sh 'pnpm build'
                }
            }
        }

        stage ("Dockerize API") {
            steps {
                dir("bdlist-backend/") {
                    sh 'docker build -t ghcr.io/shuttleday/api:latest .' 
                }
            }
        }  

        stage ("Push image to ghcr.io") {
            steps {
                dir("bdlist-backend/") {
                    sh 'docker push ghcr.io/shuttleday/api:latest' 
                }
            }
        }  
    }
    post {
        cleanup {
            sh 'docker system prune -f'
        }
    }
}